In [2]:
import pandas as pd
import json
import requests
from bs4 import BeautifulSoup

In [4]:
url = 'http://apis.data.go.kr/1360000/AsosDalyInfoService/getWthrDataList'

queryParams = '?' + \
              'ServiceKey=' + 'TG%2FeL808mmVpNQ4k7B3cHyeLV2GtdonPs0bMB88G13DxF9hUbCPmhGyVZ6h1YGrPfZ3%2BauAfGRhZQ0554hX9Vg%3D%3D' + \
              '&pageNo='+ '1' + \
              '&numOfRows='+ '999' + \
              '&dataType='+ 'JSON' + \
              '&dataCd='+ 'ASOS' + \
              '&dateCd='+ 'DAY' + \
              '&startDt='+ '20210101' + \
              '&endDt='+ '20221231' + \
              '&stnIds='+ '108' # \

In [5]:
result = requests.get(url + queryParams)
js = json.loads(result.content)
data = pd.DataFrame(js['response']['body']['items']['item'])

In [6]:
li = ['tm','avgTa','minTa','maxTa','sumRn','iscs']

data.loc[:,li]

,tm,avgTa,minTa,maxTa,sumRn,iscs
0,2021-01-01,-4.2,-9.8,1.6,,
1,2021-01-02,-5.0,-8.4,-1.4,,
2,2021-01-03,-5.6,-9.1,-2.0,,
3,2021-01-04,-3.5,-8.4,0.3,0.0,{눈}2140-{눈}{강도0}2400-
4,2021-01-05,-5.5,-9.9,-2.1,0.0,-{눈}-{눈}{강도0}0300-0420. {눈}0510-{눈}{강도0}0600-0...
...,...,...,...,...,...,...
725,2022-12-27,-2.6,-7.3,3.3,,
726,2022-12-28,-3.3,-6.0,0.1,0.1,{눈}0245-{눈}{강도0}0300-0545.
727,2022-12-29,-2.9,-7.8,2.1,0.0,{눈}1940-{눈}{강도0}2100-{눈}{강도0}2400-
728,2022-12-30,-1.8,-4.4,2.3,0.0,-{눈}-0235. {박무}0735-{박무}{강도0}0900-0910.
729,2022-12-31,-1.2,-5.1,2.1,0.0,{눈}0505-0520. {눈}0855-{눈}{강도0}0900-0915. {눈}12...

In [7]:
data[li].to_csv("weather.csv",index=False )